### ISSUE TITLE
Add support for decimal numbers

### ISSUE THREAD

**Issue by fnwirth** [prasser/easy-smpc#42]

**Comment by TKussel** [comment]
Backend support is included in branch feature/decimal (889b25bed1fabf59649f3cf21334ecab36341bcd). For now the BigInteger Interface in the Study class is marked deprecated. Using ```BigDecimal``` as input values already invokes the new functionality. Unfortunately for compatibility I was forced to use a new function name for result reconstruction: ```getAllDecResults()```. This will change back to ```getAllResults()``` when we remove the integral interface in a breaking change.
I have not changed the GUI interface yet.

**Comment by TKussel** [comment]
Done in 791ed98
