### ISSUE TITLE
Display own party

### ISSUE THREAD

**Issue by TKussel** [prasser/easy-smpc#67]
A small feature, but convenient: maybe put an arrow in front of the text field of the own party. In a distributed setting this is not a big deal, but while testing on one machine multiple windows might get confusing otherwise.

**Comment by fnwirth** [comment]
It was also a feedback of the try out last week to better visualuethe own party in the perspectives.
How can this be done in a good way?

**Comment by fnwirth** [comment]
Add a light green background for the respective textbox
