### ISSUE TITLE
Sign installers

### ISSUE THREAD

**Issue by fnwirth** [prasser/easy-smpc#71]
The installers for Windows and probably also MacOS give a warning since the code is not signed

**Comment by fnwirth** [comment]
For both OS a developer account is needed to sign the installers which is 80 or 100$ per year

**Comment by fnwirth** [comment]
> 
> 
> Thanks. I don't think that this is a problem. A short message that installers are not signed should be enough in the readme. Screenshots are not needed, as this is quite common.

Then we can close the issue

**Comment by prasser** [comment]
Only when there is a message in the readme, now. :)
