### ISSUE TITLE
Linux installer shows "Proprietary" License under Ubuntu 20.4

### ISSUE THREAD

**Issue by TKussel** [prasser/easy-smpc#78]

**Comment by fnwirth** [comment]
jpackage does not support to add a licence for the installer under Linux, only for Windows and MacOS

**Comment by TKussel** [comment]
This is the Software Installer window under Ubuntu 20.4:
![easysmpc-installer-ubuntu](https://user-images.githubusercontent.com/7169565/111178264-4183f180-85ab-11eb-8861-0c6cfca28380.png)
It's not a huge issue, we state our license in many different ways. So, "won't fix" at the moment?

**Comment by prasser** [comment]
Yeah. Let's do won't fix.
