### ISSUE TITLE
Please give visual feedback after automatically recieving messages from clipboard

### ISSUE THREAD

**Issue by TKussel** [prasser/easy-smpc#79]

**Comment by fnwirth** [comment]
I dont understand: The green labels are changed in color/intensity when a message is entered (unless there is a bug...)

**Comment by TKussel** [comment]
This works perfectly. But in our test users were quite confused by the auto insertion. Maybe a model "Auto inserted message from Bapu" or something along this line helps against the confusion.

**Comment by fnwirth** [comment]
How about adding a line with a JLabel above the 2-3 buttons in the lower part of the GUI.
This general could be filled when events happen such as Anroid "toasts"

**Comment by TKussel** [comment]
Sounds great!

**Comment by fnwirth** [comment]
Added in branch NewFeatures... will be imported soon to main
