### ISSUE TITLE
Deactivate buttons to manually recieve/send in automated mode

### ISSUE THREAD

**Issue by TKussel** [prasser/easy-smpc#81]

**Comment by prasser** [comment]
We deliberately decided to not deactivate them si that manual exchange can be done when something goes wrong. This needs to be thought through in more detail, however. Currently it's not really sound as it's not possible to manually resend messages that have already been sent automatically before.

**Comment by TKussel** [comment]
I understand the rationale to have them active. However, with no visual feedback that the program is actively awaiting/looking for messages it becomes uncertain for a user what to do. We'll have to talk about that topic.

**Comment by prasser** [comment]
I know. A spinning wheel or something the like could be a solution.

**Comment by fnwirth** [comment]
In the new branch NewFeaturesDuringProjectatjon a first version of a spinning wheel is proposed. However, there are at least two open points
- Place and design of the wheel
- The code so far checks with BusEmail.isAlive() whether the thread to check for e-mails is running. This however means that the wheel is also shown positive e.g. no internet connection would be there.

**Comment by fnwirth** [comment]
- Placed above the button
- The code now check whether a connection to the mailbox can be established
