### ISSUE TITLE
Is it possible to send the first mails also with shared mail box?

### ISSUE THREAD

**Issue by fnwirth** [prasser/easy-smpc#88]
The very first e-mails (the invitation of the creator to the participants) are send by e-mail so far. How about send them automated from the shared mailbox to the respective participants e-mails?

As far as I can see, this would not impose a confidentality problem, since every participant still keeps their share private.
It would be an issue of authentification since somebody could read the outgoing folder of the mailbox to act as another user. However, we have authentification issues in EasySMPC anyways since we are only using e-mails anyways as an authentification mechansim.

@TKussel  May I ask you kindly to double check these claims?

**Comment by TKussel** [comment]
Confidentiality wise I don't see a problem, other than impersonation attacks due to missing authentication (see issue #89).  
Practically we use the (manual) first message to configure the automatic mode for all parties.

**Comment by fnwirth** [comment]
Okay, so I will change the automated processing functionality in that sense that the the initial e-mails will be sent using the bus (and shared mailbox) but TO the actual mail addresses.
No changes after the initial sending and also no GUI changes since everytime automated processing is selected the initial mails will be sent to the actual mail addresses.

Please tell me if you do not agree

**Comment by fnwirth** [comment]
Implemented
